//! `crucible init`: scaffold a minimal manifest + measure stub in the current directory, so
//! dropping crucible onto an existing repo is dropping a file (like a justfile), not writing
//! Rust or wiring an engine integration. Modeled on `examples/counter/`, the canonical minimal
//! domain: `[repo] path = "."`, no `[workspace]` (default setup clones the repo into
//! `workspace/`), a stub judge that always reports the same score so a first dry run and
//! `crucible check` succeed before the real scoring command is hooked up.

use anyhow::{Context, Result, bail};
use std::path::Path;

pub const MANIFEST_FILE: &str = "crucible.toml";
pub const MEASURE_FILE: &str = "crucible-measure.sh";

const MANIFEST_TEMPLATE: &str = r#"# crucible.toml — generated by `crucible init`. Full contract: docs/crucible-contract.md;
# examples/counter is the minimal reference domain this mirrors.

[repo]
# This manifest lives inside the repo it targets ("."). crucible's default setup (no
# [workspace].setup_cmd) clones it into workspace/, so the agent's iterations are reversible
# git history on a clone, never your real working tree.
path = "."

[agent]
backend = "local"
# TODO: replace with the real goal for this domain (what should the agent improve?).
goal = "Describe what the agent should improve here."

[judge]
# TODO: point this at your real scoring command. It must print, as its LAST stdout line, JSON
# matching the crucible measure contract: {"valid": bool, "score": number, "solved"?: bool,
# "note"?: string}. This stub always reports the same score so `crucible check` and a first
# dry run succeed before real scoring is wired up.
measure_cmd = "./crucible-measure.sh"
direction   = "higher"
objective   = "score"

# No [world] block -> GitWorld: kept iterations commit, discards `reset --hard`.
"#;

const MEASURE_STUB: &str = r#"#!/bin/sh
# crucible measure contract stub (docs/crucible-contract.md): the engine reads the LAST stdout
# line starting with `{` as JSON {valid, score, solved?, note?}. Replace this with your real
# scoring command; keep the same last-line contract.
echo '{"valid": true, "score": 0.0, "note": "stub"}'
"#;

/// Scaffold `crucible.toml` + the measure stub in `dir`. Refuses (errors, doesn't prompt or
/// overwrite) if either target file already exists.
pub fn run(dir: &Path) -> Result<()> {
    let manifest_path = dir.join(MANIFEST_FILE);
    let measure_path = dir.join(MEASURE_FILE);
    for p in [&manifest_path, &measure_path] {
        if p.exists() {
            bail!(
                "refusing to overwrite existing file: {} (crucible init never overwrites)",
                p.display()
            );
        }
    }
    std::fs::write(&manifest_path, MANIFEST_TEMPLATE)
        .with_context(|| format!("writing {}", manifest_path.display()))?;
    std::fs::write(&measure_path, MEASURE_STUB)
        .with_context(|| format!("writing {}", measure_path.display()))?;
    set_executable(&measure_path)
        .with_context(|| format!("marking {} executable", measure_path.display()))?;

    println!(
        "wrote {} and {}",
        manifest_path.display(),
        measure_path.display()
    );
    println!(
        "next: fill in [agent].goal (and [judge].measure_cmd once you have a real gate), \
then `crucible check --manifest {}`",
        manifest_path.display()
    );
    Ok(())
}

#[cfg(unix)]
fn set_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = std::fs::metadata(path)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms)?;
    Ok(())
}

#[cfg(not(unix))]
fn set_executable(_path: &Path) -> Result<()> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn tempdir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "crucible-init-test-{name}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or_default()
        ));
        std::fs::create_dir_all(&dir).expect("mkdir tmp");
        dir
    }

    #[test]
    fn init_then_manifest_parses() {
        let dir = tempdir("parses");
        run(&dir).expect("init");
        let m = crate::manifest::Manifest::load(&dir.join(MANIFEST_FILE))
            .expect("freshly-init'd manifest must parse");
        assert_eq!(m.judge.measure_cmd, "./crucible-measure.sh");
        assert_eq!(m.repo.path.as_deref(), Some("."));
        assert!(
            m.world.snapshot_cmd.is_none() && m.world.apply_cmd.is_none(),
            "no [world] -> GitWorld"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn init_twice_errors_without_overwriting() {
        let dir = tempdir("twice");
        run(&dir).expect("first init");
        let manifest_before = std::fs::read_to_string(dir.join(MANIFEST_FILE)).unwrap();
        let err = run(&dir).expect_err("second init must refuse to overwrite");
        assert!(err.to_string().contains("refusing to overwrite"));
        let manifest_after = std::fs::read_to_string(dir.join(MANIFEST_FILE)).unwrap();
        assert_eq!(manifest_before, manifest_after, "existing file untouched");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn measure_stub_emits_the_contract() {
        let dir = tempdir("stub");
        run(&dir).expect("init");
        let out = std::process::Command::new("sh")
            .arg("-c")
            .arg("./crucible-measure.sh")
            .current_dir(&dir)
            .output()
            .expect("run stub");
        assert!(out.status.success());
        let stdout = String::from_utf8_lossy(&out.stdout);
        let v: serde_json::Value = serde_json::from_str(stdout.trim()).expect("valid json");
        assert_eq!(v["valid"], true);
        assert_eq!(v["score"], 0.0);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
