-- 0001_baseline.sql — the controller's ledger (ADR-0016 schema; ADR-0015 outer loop),
-- squashed from the SQLite migration set (0001–0029) at the Postgres cutover.
--
-- Up-only: rebuild-from-evidence is the disaster fallback (ADR-0016), not the upgrade path.
-- Every migration past this one carries the bors review rule: a NOT NULL column needs a
-- DEFAULT, or replaying against a populated ledger fails.
--
-- Conventions carried over from the SQLite era:
--   * Timestamps are TEXT, RFC3339 UTC (`…Z`), stamped by the Rust side (client::now_rfc3339).
--     RFC3339 sorts lexicographically, so TEXT comparison keeps working for cutoffs.
--   * Integers are BIGINT (the Rust side reads i64).
--   * What SQLite stored as 0/1 INTEGER flags is BOOLEAN here.

CREATE TABLE repos (
    repo                 TEXT PRIMARY KEY,
    last_seen_updated_at TEXT,
    -- Discovery iterates this repo iff watched AND NOT paused.
    watched              BOOLEAN NOT NULL DEFAULT TRUE,
    paused               BOOLEAN NOT NULL DEFAULT FALSE,
    added_by             TEXT,
    added_at             TEXT,
    closed_repaired_at   TEXT
);

CREATE TABLE issues (
    key                     TEXT PRIMARY KEY,
    repo                    TEXT NOT NULL,
    tier                    TEXT,
    status                  TEXT NOT NULL,
    priority                BIGINT NOT NULL DEFAULT 0,
    evidence_url            TEXT,
    parked_reason           TEXT,
    parked_by               TEXT CHECK (parked_by IN ('machine', 'human')),
    updated_at              TEXT NOT NULL,
    ranked_content_hash     TEXT,
    title                   TEXT,
    author                  TEXT,
    labels                  TEXT,
    grounded_content_hash   TEXT,
    upstream_updated_at     TEXT,
    scope_now_justification TEXT,
    scope_now_max_cost      DOUBLE PRECISION,
    body                    TEXT,
    pre_park_status         TEXT,
    redispatch_justification TEXT,
    input_kind              TEXT NOT NULL DEFAULT 'github',
    git_ref                 TEXT,
    codegen_contract        TEXT
);

CREATE TABLE scopes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue             TEXT NOT NULL REFERENCES issues(key),
    pack_digest       TEXT,
    check_outcome     TEXT,
    stale             BOOLEAN NOT NULL DEFAULT FALSE,
    approval_pr       TEXT,
    approved_by       TEXT,
    approved_at       TEXT,
    frozen_issue_hash TEXT,
    stale_comment_id  TEXT
);

CREATE TABLE runs (
    -- Insertion-order tiebreaker: SQLite call sites ordered by the implicit rowid; Postgres
    -- has none, so the identity column carries the "newest row wins" ordering explicitly.
    seq             BIGINT GENERATED ALWAYS AS IDENTITY,
    run_id          TEXT PRIMARY KEY,
    scope           BIGINT REFERENCES scopes(id),
    identity_digest TEXT,
    status          TEXT NOT NULL,
    pod             TEXT,
    session_uri     TEXT,
    best_score      DOUBLE PRECISION,
    cost_usd        DOUBLE PRECISION
);

CREATE TABLE candidates (
    -- Insertion-order tiebreaker (see runs.seq).
    seq      BIGINT GENERATED ALWAYS AS IDENTITY,
    run_id   TEXT NOT NULL REFERENCES runs(run_id),
    kind     TEXT,
    lane     BIGINT,
    iter     BIGINT,
    score    DOUBLE PRECISION,
    decision TEXT,
    worktree TEXT,
    sandbox  TEXT,
    pr_url   TEXT,
    branch   TEXT
);

CREATE TABLE ledger (
    ts       TEXT NOT NULL,
    run_id   TEXT,
    kind     TEXT NOT NULL,
    cost_usd DOUBLE PRECISION NOT NULL
);

CREATE TABLE work_pods (
    pod_name    TEXT PRIMARY KEY,
    kind        TEXT NOT NULL,
    issue_key   TEXT,
    state       TEXT NOT NULL,
    cost_tag    TEXT NOT NULL,
    result      TEXT,
    error       TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    terminal_at TEXT,
    cluster     TEXT NOT NULL DEFAULT 'hub'
);
CREATE INDEX work_pods_kind_state ON work_pods (kind, state);

-- Local mirror of upstream GitHub comments; id is GitHub's comment id, never generated here.
CREATE TABLE issue_comments (
    id         BIGINT PRIMARY KEY,
    issue_key  TEXT NOT NULL REFERENCES issues(key),
    author     TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    body       TEXT NOT NULL
);
CREATE INDEX issue_comments_by_issue ON issue_comments (issue_key);

CREATE TABLE scope_reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_key   TEXT NOT NULL,
    pod_name    TEXT,
    survived    BOOLEAN NOT NULL,
    report_json TEXT NOT NULL,
    created_at  TEXT NOT NULL
);
CREATE INDEX scope_reports_issue ON scope_reports (issue_key, id);

CREATE TABLE scope_transcripts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_report_id BIGINT NOT NULL REFERENCES scope_reports (id),
    issue_key       TEXT NOT NULL,
    transcript_gz   BYTEA NOT NULL,
    created_at      TEXT NOT NULL
);
CREATE INDEX scope_transcripts_issue ON scope_transcripts (issue_key, id);

CREATE TABLE pod_artifacts (
    pod        TEXT NOT NULL,
    kind       TEXT NOT NULL,
    path       TEXT NOT NULL,
    digest     TEXT NOT NULL,
    bytes      BIGINT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (pod, kind)
);
CREATE INDEX pod_artifacts_digest ON pod_artifacts (digest);

CREATE TABLE mlflow_exports (
    run_id        TEXT PRIMARY KEY REFERENCES runs(run_id),
    state         TEXT NOT NULL,
    mlflow_run_id TEXT,
    experiment_id TEXT,
    attempts      BIGINT NOT NULL DEFAULT 0,
    error         TEXT,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);
CREATE INDEX mlflow_exports_state ON mlflow_exports (state);

CREATE TABLE builds (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The scope (pack) this build blocks. Reconcile won't launch the scope's run until every build
    -- for it carries a digest_ref. (`needs` ordering across builds is a later milestone.)
    scope          BIGINT REFERENCES scopes(id),
    -- The `[build.<name>]` key, the pushed image (`image`), and the tag pushed to.
    name           TEXT NOT NULL,
    image          TEXT NOT NULL,
    tag            TEXT NOT NULL,
    -- The hash of the build's declared context — the "build-needed" identity (ADR-0018 §2). A
    -- re-dispatch of an unchanged context pushes the same tag idempotently.
    context_digest TEXT NOT NULL,
    backend        TEXT NOT NULL CHECK (backend IN ('cluster', 'github-actions')),
    state          TEXT NOT NULL DEFAULT 'pending'
                     CHECK (state IN ('pending', 'dispatched', 'succeeded', 'failed', 'timed-out')),
    -- The dispatch identity reconcile polls + startup adoption lists against: a cluster Job name or
    -- a GitHub Actions run id. NULL until dispatched.
    dispatch_id    TEXT,
    -- The pinned `image@sha256:…` resolved from the pushed tag on success (ADR-0012 consumers read it).
    digest_ref     TEXT,
    -- The build-log pointer parked as evidence on failure/timeout (ADR-0018 §4).
    evidence_url   TEXT,
    -- Failed dispatch attempts against this row. Reconcile re-drives a `pending` row every pass
    -- (crash-safe: the row is committed before the network dispatch), so a transient dispatch error
    -- charges an attempt here; after a small cap the row is failed with the error as evidence and the
    -- blocked issue parks instead of spinning — the pending-row reaping the timeout cap can't do (a
    -- never-dispatched row has no `dispatched_at` clock to run out).
    dispatch_attempts BIGINT NOT NULL DEFAULT 0,
    timeout_secs   BIGINT NOT NULL,
    created_at     TEXT NOT NULL,
    dispatched_at  TEXT,
    finished_at    TEXT,
    -- One row per (scope, build name): the reconcile driver keys the plan against existing rows by
    -- name and re-dispatches a still-`pending` row idempotently, so a re-driven insert must collide
    -- rather than fork a second row for the same declared build.
    UNIQUE (scope, name)
);
CREATE INDEX builds_state ON builds (state);
CREATE INDEX builds_scope ON builds (scope);

CREATE TABLE scenarios (
    key           TEXT PRIMARY KEY REFERENCES issues(key) ON DELETE CASCADE,
    title         TEXT NOT NULL,
    body          TEXT NOT NULL,           -- goal framing, never a solution
    created_by    TEXT NOT NULL,
    created_at    TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    -- An authoritative brief reaches the scope agent verbatim, prescriptions intact.
    authoritative BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE scenario_repos (
    key      TEXT NOT NULL REFERENCES issues(key) ON DELETE CASCADE,
    repo     TEXT NOT NULL,
    position BIGINT NOT NULL,
    PRIMARY KEY (key, position)
);

CREATE TABLE emissions (
    issue_key        TEXT NOT NULL,
    artifact         TEXT NOT NULL,
    tracker_issue_id TEXT NOT NULL,
    created_at       TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    PRIMARY KEY (issue_key, artifact)
);

CREATE TABLE run_plans (
    run_id       TEXT NOT NULL,
    plan_version BIGINT NOT NULL,
    graph_json   TEXT NOT NULL,
    PRIMARY KEY (run_id, plan_version)
);

CREATE TABLE run_task_results (
    run_id   TEXT NOT NULL,
    iter     BIGINT NOT NULL,
    task     TEXT NOT NULL,
    status   TEXT NOT NULL,
    note     TEXT NOT NULL DEFAULT '',
    cost_usd DOUBLE PRECISION,
    secs     DOUBLE PRECISION,
    PRIMARY KEY (run_id, iter, task)
);
