#![allow(clippy::disallowed_macros)]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::model::{Feedstock, ResolvedImage, generated_dir};

use crucible_capability::{CAPABILITIES_LABEL, CAPABILITIES_SCHEMA};
const INTRO_PATH: &str = "/etc/crucible/intro.md";
const INTRO_PATH_LABEL: &str = "io.crucible.intro.path";
const INTRO_DIGEST_LABEL: &str = "io.crucible.intro.digest";
/// Digest-pinned: the base is the one input that stays fixed between builds. The rpms each
/// feature installs float within it (UBI serves only the current build of a package, so an
/// exact NVR stops resolving within hours) and are recorded per image at
/// [`RPM_MANIFEST_DIR`] instead. Bump tag and digest together.
const BASE_IMAGE: &str = "registry.access.redhat.com/ubi10/ubi:10.2@sha256:229097f6000bebb77cbc83121583c4b1b1eee85742293905a8d8226a2925b3fc";
const HEADER: &str = "Generated by `cargo xtask images gen`. Edit images/features/ and images/matrix.toml, then rerun.";
/// Where the built image records the rpm set present after each feature's install, one
/// sorted `name-version-release.arch` per line per feature: the provenance an exact lock
/// used to carry, taken from what actually installed.
const RPM_MANIFEST_DIR: &str = "/usr/share/crucible/rpms";

/// Render every output file, keyed by path relative to images/generated/.
fn render(feedstock: &Feedstock) -> Result<BTreeMap<PathBuf, String>> {
    let mut files = BTreeMap::new();
    for spec in &feedstock.matrix.image {
        let image = feedstock.resolve(spec)?;
        let dir = PathBuf::from(&spec.name);
        let intro = image.intro()?;
        files.insert(dir.join("Containerfile"), containerfile(&image, &intro)?);
        files.insert(dir.join("INTRO.md"), intro);
    }
    Ok(files)
}

fn containerfile(image: &ResolvedImage, intro: &str) -> Result<String> {
    let mut out = String::new();
    let _ = writeln!(out, "# {HEADER}");
    let _ = writeln!(
        out,
        "# Build context is images/, e.g.: buildah build --layers -f generated/{}/Containerfile .",
        image.spec.name
    );
    let base = image.spec.base.as_deref().unwrap_or(BASE_IMAGE);
    let _ = writeln!(out, "ARG BASE_IMAGE={base}");
    let _ = writeln!(out, "FROM ${{BASE_IMAGE}}");

    for feature in &image.features {
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "# feature: {} — {}",
            feature.name, feature.spec.summary
        );
        for (pin, version) in &feature.spec.pins {
            let _ = writeln!(
                out,
                "ARG PIN_{}={}",
                shell_name(pin),
                image.effective_pin(pin, version)
            );
        }
        for (key, value) in &feature.spec.env {
            let _ = writeln!(out, "ENV {key}={value}");
        }
        for repofile in &feature.spec.repofiles {
            let _ = writeln!(out, "COPY {repofile} /etc/yum.repos.d/");
        }
        let staged = format!("/tmp/feature-{}", feature.name);
        if feature.install {
            let _ = writeln!(out, "COPY features/{}/ {staged}/", feature.name);
        }
        let mut steps = Vec::new();
        let mut rpms: Vec<&str> = feature.spec.rpms.iter().map(String::as_str).collect();
        rpms.sort_unstable();
        if !rpms.is_empty() {
            steps.push(format!("dnf -y install {}", rpms.join(" ")));
            steps.push("dnf clean all".to_string());
            steps.push(format!("mkdir -p {RPM_MANIFEST_DIR}"));
            steps.push(format!(
                "rpm -qa --qf '%{{NAME}}-%{{VERSION}}-%{{RELEASE}}.%{{ARCH}}\\n' | sort > {RPM_MANIFEST_DIR}/{}",
                feature.name
            ));
        }
        if feature.install {
            steps.push(format!("bash {staged}/install.sh"));
            steps.push(format!("rm -rf {staged}"));
        }
        if !steps.is_empty() {
            // Heredoc RUN (dockerfile 1.4+, buildah >= 1.33): one script block per
            // feature layer instead of an &&-chain.
            let _ = writeln!(out, "RUN <<EOF");
            let _ = writeln!(out, "#!/bin/bash");
            let _ = writeln!(out, "set -euo pipefail");
            for step in &steps {
                let _ = writeln!(out, "{step}");
            }
            let _ = writeln!(out, "EOF");
        }
    }

    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "# The agent orientation document (C-INSTRUCTIONS): its path and content"
    );
    let _ = writeln!(
        out,
        "# digest are published as labels so the composed instructions are provable."
    );
    let intro_digest = {
        use sha2::Digest as _;
        format!("sha256:{:x}", sha2::Sha256::digest(intro.as_bytes()))
    };
    let _ = writeln!(
        out,
        "COPY generated/{}/INTRO.md {INTRO_PATH}",
        image.spec.name
    );
    let _ = writeln!(
        out,
        "LABEL {INTRO_PATH_LABEL}={INTRO_PATH} \\\n      {INTRO_DIGEST_LABEL}={intro_digest}"
    );

    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "# The self-description the controller preflight reads (C-CAPABILITIES)."
    );
    let doc = capability_doc(image)?;
    let compact = serde_json::to_string(&doc)?;
    if compact.contains('\'') {
        bail!(
            "image {}: capability doc contains a single quote",
            image.spec.name
        );
    }
    let _ = writeln!(out, "LABEL {CAPABILITIES_LABEL}='{compact}'");
    Ok(out)
}

fn capability_doc(image: &ResolvedImage) -> Result<crucible_capability::CapabilityDoc> {
    Ok(crucible_capability::CapabilityDoc {
        features: image.features.iter().map(|f| f.name.clone()).collect(),
        image: image.spec.name.clone(),
        predicates: image
            .predicates()?
            .into_iter()
            .map(|(p, v)| (p.to_string(), v))
            .collect(),
        schema: CAPABILITIES_SCHEMA.to_string(),
    })
}

fn shell_name(pin: &str) -> String {
    pin.replace('-', "_").to_uppercase()
}

pub fn write(feedstock: &Feedstock, root: &Path) -> Result<()> {
    let dir = generated_dir(root);
    let files = render(feedstock)?;
    if dir.exists() {
        fs::remove_dir_all(&dir).with_context(|| format!("clearing {}", dir.display()))?;
    }
    for (rel, content) in &files {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
    }
    println!("wrote {} files under {}", files.len(), dir.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::fs;

    use crate::model::Feedstock;
    use crate::model::testutil::feedstock;

    const MATRIX: &str =
        "schema = 1\n\n[[image]]\nname = \"sandbox-go-cc\"\nfeatures = [\"claude-code\", \"go\"]\n";

    #[test]
    fn features_order_canonically_and_render_deterministically() {
        let dir = tempfile::tempdir().unwrap();
        let fs_ = feedstock(dir.path(), MATRIX);
        let files = crate::generate::render(&fs_).unwrap();
        let cf = &files[std::path::Path::new("sandbox-go-cc/Containerfile")];
        // Canonical order by layer: base, go, claude-code — regardless of matrix order.
        let base = cf.find("# feature: base").unwrap();
        let go = cf.find("# feature: go").unwrap();
        let cc = cf.find("# feature: claude-code").unwrap();
        assert!(base < go && go < cc, "bad order:\n{cf}");
        assert!(cf.contains("ARG PIN_GO=1.25.11"));
        assert!(cf.contains("ENV GOTOOLCHAIN=local"));
        assert!(cf.contains("ARG PIN_CLAUDE_CODE=2.0.1"));
        assert!(cf.contains("dnf -y install git jq"));
        assert!(cf.contains(&format!(
            "rpm -qa --qf '%{{NAME}}-%{{VERSION}}-%{{RELEASE}}.%{{ARCH}}\\n' | sort > {}/base",
            crate::generate::RPM_MANIFEST_DIR
        )));
        assert!(cf.contains("RUN <<EOF\n#!/bin/bash\nset -euo pipefail\n"));
        assert_eq!(files, crate::generate::render(&fs_).unwrap());
    }

    #[test]
    fn capability_doc_unions_predicates() {
        let dir = tempfile::tempdir().unwrap();
        let fs_ = feedstock(dir.path(), MATRIX);
        let files = crate::generate::render(&fs_).unwrap();
        let cf = &files[std::path::Path::new("sandbox-go-cc/Containerfile")];
        let label = cf
            .lines()
            .find_map(|l| {
                l.strip_prefix(&format!(
                    "LABEL {}='",
                    crucible_capability::CAPABILITIES_LABEL
                ))
            })
            .unwrap()
            .trim_end_matches('\'');
        let doc: serde_json::Value = serde_json::from_str(label).unwrap();
        assert_eq!(doc["schema"], crucible_capability::CAPABILITIES_SCHEMA);
        assert_eq!(doc["predicates"]["toolchain.go"], "1.25");
        assert_eq!(doc["predicates"]["agent.claude-code"], "2");
        assert_eq!(doc["predicates"]["vcs.git"], "2");
        assert_eq!(doc["features"][0], "base");
    }

    #[test]
    fn conflicting_predicate_versions_fail_resolution() {
        let dir = tempfile::tempdir().unwrap();
        let features = dir.path().join("features");
        for (name, version) in [("base", "2"), ("other-git", "3")] {
            let d = features.join(name);
            fs::create_dir_all(&d).unwrap();
            fs::write(
                d.join("feature.toml"),
                format!(
                    "summary = \"x\"\nlayer = 5\n\n[capabilities]\n\"vcs.git\" = \"{version}\"\n"
                ),
            )
            .unwrap();
        }
        fs::write(
            dir.path().join("matrix.toml"),
            "schema = 1\n\n[[image]]\nname = \"clash\"\nfeatures = [\"other-git\"]\n",
        )
        .unwrap();
        let err = Feedstock::load(dir.path()).unwrap_err().to_string();
        assert!(err.contains("vcs.git"), "unexpected error: {err}");
    }
}
